general.import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
dimensions = { columns = 120, lines = 40 }

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"
size = 15
